### ISSUE TITLE
um...unexpected token at 'Not Found'

### ISSUE THREAD

**Issue by djbjoo** [sferik/mlb-ruby#7]
```
% ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

% irb
require 'mlb'
MLB::Team.all.first.name
Faraday::ParsingError: 757: unexpected token at 'Not Found'
    from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/mlb-0.7.0/lib/mlb/request.rb:9:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/mlb-0.7.0/lib/mlb/team.rb:47:in `results_from_freebase'
    from /Library/Ruby/Gems/2.0.0/gems/mlb-0.7.0/lib/mlb/team.rb:28:in `all'
    from (irb):3
    from /usr/bin/irb:12:in `<main>'irb(main):004:0
```

**Comment by K1TCH** [comment]
I second this. Getting a similar error when trying to run the same code.

![image](https://user-images.githubusercontent.com/8645722/27068360-5ed351f0-4fd5-11e7-9944-0fcf2044cd72.png)

Please help

**Comment by sbull** [comment]
This was dependent on the now-defunct Freebase service. PR #8 removes this dependency.

**Comment by sferik** [comment]
I'm rewriting this now to use the [MLB Data API](https://appac.github.io/mlb-data-api-docs/).
